### ISSUE TITLE
Access to user permissions required?

### ISSUE THREAD

**Issue by katrinkerber** [lindseydiloreto/craft-autoassignusergroup#3]
Hi Lindsey,

I've just tried out your plugin. I have one user groups called 'Admins' and I want Admins to be able to create new users that also automatically belong to the 'Admins' group. I don't want them to have access to the user permission settings.

I found that when an existing admin creates a new admin account, then that new account will only be auto-assigned to the 'Admins' group when the `Assign user groups and permissions` option is checked within the group’s settings. If it is left unchecked, the new user isn't assigned to a group.

Is there a way to auto-assign the group with that setting being left unchecked for the group?

**Comment by lindseydiloreto** [comment]
Hi Katrin,

At the moment, that's not currently possible. That's actually more of a limitation of **Craft itself**, rather than the plugin. The new user registration process takes place in a very particular way, and this plugin capitalizes on a small "loophole"... it's unfortunately not possible to bend the process much further.

Instead, I'd recommend using [CP CSS](https://github.com/lindseydiloreto/craft-cpcss) or [CP JS](https://github.com/lindseydiloreto/craft-cpjs) to simply **hide** that checkbox.

Hope that helps!

**Comment by katrinkerber** [comment]
Ah I see, thank you very much Lindsey.

Great idea, I'll use your CP CSS plugin which I have already installed for this :)
